#pragma once
#include "agisga.h"

enum custom_keycodes {
  KC_AT_SPECIAL = SAFE_RANGE,
  KC_ELLIPSIS,
  KC_AUTOCLOS_PAREN,
  KC_AUTOCLOS_SQBRA,
  KC_AUTOCLOS_CURLYBRA,
  KC_AUTOCLOS_QUOTE,
  KC_COLONQ,
  KC_COLONQEX,
  KC_COLONWQ,
  KC_COLONW,
  KC_DOTSPC,
  KC_FIFTEENSTARS,
  KC_TODO,
  KC_TABEDIT,
};
